sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t alansaldivar87/docker-fullstack-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alansaldivar87/docker-fullstack-react npm run test