sudo: required
services:
  - docker

before_install:
  - docker build -t alansaldivar87/docker-fullstack-react -f Dockerfile .

script:
  - docker run -e CI=true alansaldivar87/docker-fullstack-react npm run test